/**
 * Framework-agnostic type definitions for collection filters, swatches,
 * and attribute data. These mirror the shapes generated by GraphQL codegen
 * so that generated types are structurally assignable without explicit coupling.
 */

// ---------------------------------------------------------------------------
// Swatch Data
// ---------------------------------------------------------------------------

export type SwatchData = {
  hex?: string | null;
  imageUrl?: string | null;
  text?: string | null;
};

// ---------------------------------------------------------------------------
// Filter Option
// ---------------------------------------------------------------------------

export type FilterOption = {
  id: string;
  code: string;
  label: string;
  isApplied: boolean;
  itemCount?: number | null;
  swatch?: SwatchData | null;
};

// ---------------------------------------------------------------------------
// Filter Interfaces (base shapes)
// ---------------------------------------------------------------------------

export type CollectionFilterAppliedInterface = {
  __typename?: string;
  code: string;
  label: string;
  includeInFilters: boolean;
  renderer?: string | null;
  type: string;
};

export type CollectionFilterAvailableInterface = {
  __typename?: string;
  code: string;
  label: string;
  includeInFilters: boolean;
  renderer?: string | null;
  type: string;
};

// ---------------------------------------------------------------------------
// Concrete Filter Types
// ---------------------------------------------------------------------------

export type CollectionFilterAppliedOption = CollectionFilterAppliedInterface & {
  __typename?: 'CollectionFilterAppliedOption';
  isSearchable: boolean;
  options: FilterOption[];
};

export type CollectionFilterAvailableOption =
  CollectionFilterAvailableInterface & {
    __typename?: 'CollectionFilterAvailableOption';
    isSearchable: boolean;
    options: FilterOption[];
  };

export type CollectionFilterAppliedBoolean =
  CollectionFilterAppliedInterface & {
    __typename?: 'CollectionFilterAppliedBoolean';
    appliedValue: boolean;
    trueLabel: string;
    falseLabel: string;
  };

export type CollectionFilterAvailableBoolean =
  CollectionFilterAvailableInterface & {
    __typename?: 'CollectionFilterAvailableBoolean';
    trueItemCount?: number | null;
    falseItemCount?: number | null;
    trueLabel: string;
    falseLabel: string;
  };

export type CollectionFilterAppliedRange = CollectionFilterAppliedInterface & {
  __typename?: 'CollectionFilterAppliedRange';
};

export type CollectionFilterAvailableRange =
  CollectionFilterAvailableInterface & {
    __typename?: 'CollectionFilterAvailableRange';
  };

// ---------------------------------------------------------------------------
// Union Types
// ---------------------------------------------------------------------------

export type CollectionFilterApplied =
  | CollectionFilterAppliedOption
  | CollectionFilterAppliedBoolean
  | CollectionFilterAppliedRange;

export type CollectionFilterAvailable =
  | CollectionFilterAvailableOption
  | CollectionFilterAvailableBoolean
  | CollectionFilterAvailableRange;

// ---------------------------------------------------------------------------
// Filter Condition Enum
// ---------------------------------------------------------------------------

export enum CollectionFilterCondition {
  Eq = 'eq',
  Gt = 'gt',
  Gteq = 'gteq',
  In = 'in',
  Like = 'like',
  Lt = 'lt',
  Lteq = 'lteq',
  Neq = 'neq',
  Nil = 'nil',
  Nin = 'nin',
  Nlike = 'nlike',
  NotNil = 'notNil',
}

// ---------------------------------------------------------------------------
// Filter Chips
// ---------------------------------------------------------------------------

export type FilterChip = {
  filterCode: string;
  label: string;
  optionId?: string;
};

// ---------------------------------------------------------------------------
// Sort Orders
// ---------------------------------------------------------------------------

export type SortOrder = {
  code: string;
  direction: string;
  label: string;
};

// ---------------------------------------------------------------------------
// Attribute & Swatch Config
// ---------------------------------------------------------------------------

export type AttributeSwatchConfig = {
  code: string;
  swatch?: {
    isEnabled?: boolean | null;
    filterRenderer?: string | null;
    listRenderer?: string | null;
    detailRenderer?: string | null;
  } | null;
};

export type ProductAttributeData = {
  id: string;
  code: string;
  label: string;
  type: string;
  isFilterable: boolean;
  isSortable: boolean;
  options: {
    id: string;
    code: string;
    label: string;
    swatch?: SwatchData | null;
  }[];
  swatch?: AttributeSwatchConfig['swatch'];
};
